config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => "homes#top"
  get "/books" => "books#index"
  post "books" => "books#create"
  resources :all_books, only: [:index, :create, :update],as: "all_book"
  patch "books/:id" => "books#update",as: "update_book"
  patch "books/:id/edit" => "books#update"
  delete "books/:id" => "books#destroy",as: "destroy_book"
  get "books/:id" =>"books#show",as: "book"
  get "books/:id/edit" =>"books#edit",as: "edit_book"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book=Book.new(book_params)
    if @book.save
      flash[:notice]="Book was successfully created."
      redirect_to @book
    else
      @books = Book.all
      render :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]="successfully edited"
      redirect_to @book
    else
      flash.now[:notice]="error"
      render :edit
    end
  end
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to "/books"
  end
  private
  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book,url: edit_book_path(@book.id), method: :patch do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %><br>
  <%= f.submit "Update Book" %>
<% end %>
<div class="button-group">
  <%= link_to "Show", book_path(@book.id), class: "button" %>
  <span>|</span>
  <%= link_to "Back", books_path, class: "button" %>
</div>

app/views/books/index.html.erb
<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td class="action-link"><%= link_to "Show", book_path(book.id) %></td>
      <td class="action-link"><%= link_to "Edit", edit_book_path(book.id) %></td>
      <td class="action-link"><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, data: { confirm: "本当に削除しますか" } %></td>
    </tr>
  <% end %>
</table>
<h1>New book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book, url: books_path,method: :post do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %> <br>
  <%= f.submit "Create Book" %>
<% end %>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<p>Title: <%= @book.title %></p>
<p>Body: <%= @book.body %></p>
<div class="button-group">
  <%= link_to "Edit",edit_book_path(@book.id), class: "button" %>
  <span>|</span>
  <%= link_to "Back", books_path, class: "button" %>
</div>

app/views/homes/top.html.erb
<body>
  <h1>ようこそ Bookersへ！</h1>
  <p><futoji>Bookers</futoji>では、さまざまな書籍に関するあなたの意見や</p>
  <p>印象を共有し交換することができます</p>
  <p><a href="/books">start</a></p>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
      <% flash.each do |message_type, message| %>
      <div class="flash-message <%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
   </main>
  </body>
</html>